definitions:
  errors.ApiError:
    properties:
      error:
        type: string
      message:
        type: string
      status:
        type: integer
    type: object
  handlers.Cat:
    properties:
      name:
        type: string
      type:
        type: string
    type: object
  handlers.Dog:
    properties:
      name:
        type: string
      type:
        type: string
    type: object
  handlers.Hamster:
    properties:
      name:
        type: string
      type:
        type: string
    type: object
  handlers.LoginStruct:
    properties:
      message:
        type: string
      token:
        type: string
    type: object
info:
  contact: {}
paths:
  /admin/main:
    get:
      consumes:
      - application/json
      description: Access to mainadmin page
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: MainAdmin
  /cats:
    post:
      consumes:
      - application/json
      description: AddCat
      parameters:
      - description: cat
        in: body
        name: cat
        required: true
        schema:
          $ref: '#/definitions/handlers.Cat'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: AddCat
  /cats/{data}:
    get:
      consumes:
      - application/json
      description: GetCats
      parameters:
      - description: name
        in: query
        name: name
        required: true
        type: string
      - description: type
        in: query
        name: type
        required: true
        type: string
      - description: data
        in: path
        name: data
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: GetCats
  /cookie/main:
    get:
      consumes:
      - application/json
      description: Access to MainCookie page
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: MainCookie
  /dogs:
    post:
      consumes:
      - application/json
      description: AddDog
      parameters:
      - description: dog
        in: body
        name: dog
        required: true
        schema:
          $ref: '#/definitions/handlers.Dog'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: AddDog
  /hamsters:
    post:
      consumes:
      - application/json
      description: AddHamster
      parameters:
      - description: hamster
        in: body
        name: hamster
        required: true
        schema:
          $ref: '#/definitions/handlers.Hamster'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: AddHamster
  /hi:
    get:
      consumes:
      - application/json
      description: Access to Hi page
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: HI
  /jwt/main:
    get:
      consumes:
      - application/json
      description: Access to MainJWT page
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: MainJWT
  /login:
    get:
      consumes:
      - application/json
      description: Login by basic auth
      parameters:
      - description: Username
        in: query
        name: username
        required: true
        type: string
      - description: Password
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.LoginStruct'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/errors.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.ApiError'
      summary: Login
swagger: "2.0"
